# Sitio
title: "Iván Blánquez Romero"
description: "Personal Website"
baseurl: "" # Deja esto vacío si es el repositorio raíz
url: "https://ivanblanquez.github.io" # Cambia esto por tu URL de GitHub Pages

# Autor
author: 
  name: "Iván Blánquez Romero"
  email: "ivan.blanquez@gmail.com"
  social:
    x: "https://x.com/ivanblanquez"
    linkedin: "https://www.linkedin.com/in/ivanblanquez"
    devto: "https://dev.to/ivanblanquez"
    github: "https://github.com/ivanblanquez"
    stackshare: "https://stackshare.io/IvanBlanquez/my-personal-stack"

# Tema
theme: minima

# Configuración de plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configuración de Markdown
markdown: kramdown
highlighter: rouge

# Configuración de enlaces
permalink: pretty

# Secciones de navegación
nav_links:
  - title: "About Me"
    url: "/"
  - title: "Publications"
    url: "/publications/"
  - title: "Talks"
    url: "/talks/"
  - title: "CV"
    url: "/cv/"
  - title: "Repositories"
    url: "/repositories/"
  - title: "Certifications & Badges"
    url: "/certifications-and-badges/"
