title: "Iván Blánquez Romero"
description: "Personal Website"
baseurl: "" # Deja esto vacío si es el repositorio raíz
url: "https://ivanblanquez.github.io" # Cambia esto por tu URL de GitHub Pages
theme: minima
author: 
  name: "Iván Blánquez Romero"
  email: "ivanblanquez@example.com"
  social:
    x: "https://x.com/tuusuario"
    linkedin: "https://www.linkedin.com/in/tuusuario"
    devto: "https://dev.to/tuusuario"
    github: "https://github.com/tuusuario"
